image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: emcmongoose/mongoose
  IMAGE_FILE_NAME: build/mongoose.tar
  JAVA_HOME: /opt/jdk-11.0.2+9
  ROBOTEST_CONTAINER_WORKING_DIR: /root/mongoose
  SERVICE_HOST: docker # should be used instead of the "localhost"/"127.0.0.1" in GL CI

services:
  - docker:dind

stages:
  - build
  - test # unit/integration tests
  - build_docker_image
  - test_functional # functional containerized tests
  - deploy

before_script:
  - apk add curl
  - curl -Lks https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_9.tar.gz -o /tmp/jdk11.tgz
  - mkdir /opt
  - tar xvf /tmp/jdk11.tgz -C /opt
  - export PATH=${PATH}:${JAVA_HOME}/bin
  - cat ${JAVA_HOME}/bin/java
  - ${JAVA_HOME}/bin/java -version

build:
  stage: build
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
      - build/libs/mongoose-*.jar

test_unit:
  stage: test
  script:
    - ./gradlew test

test_integration:
  stage: test
  script:
    - ./gradlew integrationTest

build_docker_image:
  stage: build_docker_image
  variables:
    DOCKERFILE: Dockerfile
  script:
    - docker build -f docker/${DOCKERFILE} -t ${IMAGE_NAME}:${CI_COMMIT_SHA} .
    - docker save ${IMAGE_NAME}:${CI_COMMIT_SHA} > ${IMAGE_FILE_NAME}
  artifacts:
    paths:
     - ${IMAGE_FILE_NAME}

.test_robot:
  stage: test_functional
  variables:
    HOST_WORKING_DIR: ${CI_PROJECT_DIR}
    MONGOOSE_IMAGE_VERSION: ${CI_COMMIT_SHA}
    PYTHONPATH: ${PYTHONPATH}:/usr/lib/python2.7/site-packages:src/test/robot/lib
  before_script:
    - apk add --no-cache --update python py-pip
    - pip install -U virtualenv
    - pip install -U requests
    - pip install -U robotframework
    - pip install -U robotframework-requests
    - pip install -U robotframework-csvlibrary
  script:
    - export MONGOOSE_VERSION=$(cat src/main/resources/config/defaults.json | grep version | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - export MONGOOSE_IMAGE_VERSION=${CI_COMMIT_SHA}
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker load < ${IMAGE_FILE_NAME}
    - robot --outputdir build/robotest --suite ${SUITE} --include ${TEST} src/test/robot
  after_script:
    - rebot build/robotest/output.xml
  artifacts:
    paths:
      - build/robotest/*.html
    when: on_failure

test_api_remote_logs:
  extends: .test_robot
  variables:
    SUITE: api.remote
    TEST: logs

test_api_remote_config:
  extends: .test_robot
  variables:
    SUITE: api.remote
    TEST: config

test_api_remote_run:
  extends: .test_robot
  variables:
    SUITE: api.remote
    TEST: run

test_api_storage_s3:
  extends: .test_robot
  variables:
    SUITE: api.storage
    TEST: s3

test_api_storage_swift:
  extends: .test_robot
  variables:
    SUITE: api.storage
    TEST: swift

deploy_to_maven_repo:
  stage: deploy
  script: # TODO
    - echo TODO
  only:
    - tags

deploy_to_docker_hub:
  stage: deploy
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker load < ${IMAGE_FILE_NAME}
    - docker tag ${IMAGE_NAME}:${CI_COMMIT_SHA} ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker tag ${IMAGE_NAME}:${CI_COMMIT_SHA} ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:latest
  only:
    - tags
