image:
  - Visual Studio 2017

environment:
  JAVA_HOME: C:\Progra~1\Java\jdk11
  HOME_DIR: C:\projects\mongoose
  PATH_TO_JAR: build\libs\mongoose-*.jar
  PATH_TO_ARTIFACTS: C:\projects\mongoose\build\robotest
  PATH: %PATH%;C:\Python37-x64\scripts

build: off
build_script:
  - cmd: cd %HOME_DIR%
  - cmd: gradlew.bat clean jar

before_test:
  - ps: |
      [Environment]::SetEnvironmentVariable("PATH", $env:PATH + ";C:\Python37-x64\scripts", "Machine")
  - ps: C:\Python37-x64\scripts\pip install -U virtualenv
  - ps: C:\Python37-x64\scripts\pip install -U requests
  - ps: C:\Python37-x64\scripts\pip install -U robotframework
  - ps: C:\Python37-x64\scripts\pip install -U robotframework-requests
  - ps: C:\Python37-x64\scripts\pip install -U robotframework-csvlibrary
  - cmd: set PYTHONPATH=%HOME_DIR%\src\test\robot\lib;C:\Python37-x64\lib\site-packages
  - cmd: mkdir %PATH_TO_ARTIFACTS%
  - cmd: type nul > %PATH_TO_ARTIFACTS%\report.html
  - cmd: type nul > %PATH_TO_ARTIFACTS%\output.xml
  - cmd: type nul > %PATH_TO_ARTIFACTS%\log.html

test_script:
  - cmd: robot --outputdir %PATH_TO_ARTIFACTS% --suite api.storage --include "fs win" src\test\robot

artifacts:
  - path: build\robotest\
