image:
  - Visual Studio 2017

environment:
  JAVA_HOME: C:\Progra~1\Java\jdk11
  HOME_DIR: C:\projects\mongoose
  PATH_TO_JAR: build\libs\mongoose-*.jar
  PATH_TO_ARTIFACTS: C:\projects\mongoose\build\robotest
  PYTHON: "C:\\Python37-x64"
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64

build: off
build_script:
  - cmd: cd %HOME_DIR%
  - cmd: gradlew.bat clean jar

before_test:
  - cmd: set PYTHONPATH=%HOME_DIR%\base\src\test\robot\lib;C:\Python37-x64\lib\site-packages
  - cmd: set PATH=%PATH%;C:\Python37-x64;C:\Python37-x64\Scripts
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "%PYTHON%\\python.exe -m pip install -U virtualenv"
  - cmd: "%PYTHON%\\python.exe -m pip install -U requests"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework-requests"
  - cmd: mkdir %PATH_TO_ARTIFACTS%
  - cmd: type nul > %PATH_TO_ARTIFACTS%\report.html
  - cmd: type nul > %PATH_TO_ARTIFACTS%\output.xml
  - cmd: type nul > %PATH_TO_ARTIFACTS%\log.html

test_script:
  - cmd: robot --outputdir %PATH_TO_ARTIFACTS% --suite api.storage --include "fs win" base\src\test\robot

artifacts:
  - path: C:\projects\mongoose\build\robotest\log.html
