apiVersion: v1
kind: Pod
metadata:
  name: mongoose
  namespace: mongoose
spec:
#  parallelism: 2
  containers:
  - image: emcmongoose/mongoose
    name: mongoose
    args:
    - --storage-driver-type=dummy-mock
    - --load-step-limit-time=1m
  restartPolicy: OnFailure
  nodeSelector:
    hostname: data-domain-dev-vm
